
name: CMake Build and Release

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            compiler: msvc
            cpp_compiler: cl
            c_compiler: cl
            artifact_name: WormsServer-Windows
            binary_path: build/Release/WormsServer.exe

          - os: ubuntu-latest
            compiler: gcc
            cpp_compiler: g++
            c_compiler: gcc
            artifact_name: WormsServer-Linux
            binary_path: build/WormsServer

    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        shell: bash
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Cache vcpkg packages
        uses: actions/cache@v4
        with:
          path: |
            ./vcpkg/installed
            ${{ github.workspace }}/.cmake
          key: vcpkg-${{ matrix.os }}-${{ hashFiles('vcpkg.json') }}

      - name: Install dependencies
        shell: bash
        run: |
          ./vcpkg/vcpkg install --triplet=${{ runner.os == 'Windows' && 'x64-windows' || 'x64-linux' }}

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Create Distribution Directory
        shell: bash
        run: |
          mkdir -p dist/${{ matrix.artifact_name }}
          if [ "${{ runner.os }}" == "Windows" ]; then
            cp build/Release/WormsServer.exe dist/${{ matrix.artifact_name }}/
            cp vcpkg/installed/x64-windows/bin/*.dll dist/${{ matrix.artifact_name }}/
          else
            cp build/WormsServer dist/${{ matrix.artifact_name }}/
          fi

      - name: Create Archive
        shell: bash
        run: |
          cd dist
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a -tzip "${{ matrix.artifact_name }}.zip" "${{ matrix.artifact_name }}"
          else
            tar -czf "${{ matrix.artifact_name }}.tar.gz" "${{ matrix.artifact_name }}"
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}.*
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*.zip
            artifacts/**/*.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true